apiVersion: v1
kind: Service
metadata:
  name: dupless-ks-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30003
  selector:
    app: dupless-ks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dupless-ks-deployment
  labels:
    app: dupless-ks
spec:
  selector:
    matchLabels:
      app: dupless-ks
  replicas: 2
  template:
    metadata:
      labels:
        app: dupless-ks
    spec:
      containers:
        - name: dupless-ks
          image: 826148267/gdbigdata:gdbd-dupless-ks-k8s-1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhubcred
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname  # 同一拓扑域
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - dupless-ks
              weight: 100