spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allow-credentials: true
            allowed-headers: "*"
            allowed-methods: "*"
            expose-headers: "*"
            max-age: 1000
      discovery:
        locator:
          enabled: true # 根据服务名产生默认路由规则，生产时不建议开启，应该以为白名单的形式定义路由规则
          lower-case-service-id: true # 因为eureka服务名大学，路径是小写，这时大小写自动转换很好用

server:
  port: 17001

logging:
  file:
    name: /gdbigdata/gateway17001/gdbd-gateway17001-log.txt

eureka:
  client:
    service-url: http://106.14.196.53:17000/eureka/,http://120.24.25.157:17000/eureka/