logging:
  file:
    name: /gdbigdata/duplesscspserver/gdbd-dcs-log.txt
  level:
    edu.jnu: info

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-0.eureka-server:17000/eureka/,http://eureka-server-1.eureka-server:17000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}.${server.port}

swagger:
  enable: false