apiVersion: v1
kind: Service
metadata:
  name: expose-eureka-service
spec:
  type: NodePort
  selector:
    app: eureka-server
  ports:
    - port: 17000
      targetPort: 17000
      nodePort: 30002
      protocol: TCP